server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    serviceUrl:
      defaultZone: http://single:1111/eureka/

spring:
  application:
    name: my-service

